/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Course} from './model/Course';
import {HTML} from './model/HTML';
import {LoginStatus} from './model/LoginStatus';
import {Selection} from './model/Selection';
import {User} from './model/User';
import {AuthApi} from './api/AuthApi';
import {CourseApi} from './api/CourseApi';
import {HTMLApi} from './api/HTMLApi';
import {SelectionApi} from './api/SelectionApi';

/**
* The_API_for_the_Maryams_homework.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var StudentCourses = require('index'); // See note below*.
* var xxxSvc = new StudentCourses.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new StudentCourses.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new StudentCourses.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new StudentCourses.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Course model constructor.
     * @property {module:model/Course}
     */
    Course,

    /**
     * The HTML model constructor.
     * @property {module:model/HTML}
     */
    HTML,

    /**
     * The LoginStatus model constructor.
     * @property {module:model/LoginStatus}
     */
    LoginStatus,

    /**
     * The Selection model constructor.
     * @property {module:model/Selection}
     */
    Selection,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The CourseApi service constructor.
    * @property {module:api/CourseApi}
    */
    CourseApi,

    /**
    * The HTMLApi service constructor.
    * @property {module:api/HTMLApi}
    */
    HTMLApi,

    /**
    * The SelectionApi service constructor.
    * @property {module:api/SelectionApi}
    */
    SelectionApi
};
