/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StudentCourses);
  }
}(this, function(expect, StudentCourses) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Selection', function() {
      beforeEach(function() {
        instance = new StudentCourses.Selection();
      });

      it('should create an instance of Selection', function() {
        // TODO: update the code to test Selection
        expect(instance).to.be.a(StudentCourses.Selection);
      });

      it('should have the property student (base name: "student")', function() {
        // TODO: update the code to test the property student
        expect(instance).to.have.property('student');
        // expect(instance.student).to.be(expectedValueLiteral);
      });

      it('should have the property course (base name: "course")', function() {
        // TODO: update the code to test the property course
        expect(instance).to.have.property('course');
        // expect(instance.course).to.be(expectedValueLiteral);
      });

    });
  });

}));
