/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Course model module.
 * @module model/Course
 * @version 1.0.0
 */
export class Course {
  /**
   * Constructs a new <code>Course</code>.
   * @alias module:model/Course
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Course</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Course} obj Optional instance to populate.
   * @return {module:model/Course} The populated <code>Course</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Course();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('teacher_name'))
        obj.teacherName = ApiClient.convertToType(data['teacher_name'], 'String');
      if (data.hasOwnProperty('weak_day'))
        obj.weakDay = ApiClient.convertToType(data['weak_day'], 'Number');
      if (data.hasOwnProperty('start_time'))
        obj.startTime = ApiClient.convertToType(data['start_time'], 'String');
      if (data.hasOwnProperty('end_time'))
        obj.endTime = ApiClient.convertToType(data['end_time'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Course.prototype.id = undefined;

/**
 * @member {String} name
 */
Course.prototype.name = undefined;

/**
 * @member {String} teacherName
 */
Course.prototype.teacherName = undefined;

/**
 * @member {Number} weakDay
 */
Course.prototype.weakDay = undefined;

/**
 * @member {String} startTime
 */
Course.prototype.startTime = undefined;

/**
 * @member {String} endTime
 */
Course.prototype.endTime = undefined;

