/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The HTML model module.
 * @module model/HTML
 * @version 2.0.0
 */
export class HTML {
  /**
   * Constructs a new <code>HTML</code>.
   * @alias module:model/HTML
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>HTML</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HTML} obj Optional instance to populate.
   * @return {module:model/HTML} The populated <code>HTML</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HTML();
    }
    return obj;
  }
}
