/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The LoginStatus model module.
 * @module model/LoginStatus
 * @version 2.0.0
 */
export class LoginStatus {
  /**
   * Constructs a new <code>LoginStatus</code>.
   * @alias module:model/LoginStatus
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoginStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginStatus} obj Optional instance to populate.
   * @return {module:model/LoginStatus} The populated <code>LoginStatus</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginStatus();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * @member {String} token
 */
LoginStatus.prototype.token = undefined;

/**
 * @member {module:model/User} user
 */
LoginStatus.prototype.user = undefined;

