# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Selection(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student: int=None, course: int=None):  # noqa: E501
        """Selection - a model defined in Swagger

        :param student: The student of this Selection.  # noqa: E501
        :type student: int
        :param course: The course of this Selection.  # noqa: E501
        :type course: int
        """
        self.swagger_types = {
            'student': int,
            'course': int
        }

        self.attribute_map = {
            'student': 'student',
            'course': 'course'
        }
        self._student = student
        self._course = course

    @classmethod
    def from_dict(cls, dikt) -> 'Selection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Selection of this Selection.  # noqa: E501
        :rtype: Selection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student(self) -> int:
        """Gets the student of this Selection.


        :return: The student of this Selection.
        :rtype: int
        """
        return self._student

    @student.setter
    def student(self, student: int):
        """Sets the student of this Selection.


        :param student: The student of this Selection.
        :type student: int
        """

        self._student = student

    @property
    def course(self) -> int:
        """Gets the course of this Selection.


        :return: The course of this Selection.
        :rtype: int
        """
        return self._course

    @course.setter
    def course(self, course: int):
        """Sets the course of this Selection.


        :param course: The course of this Selection.
        :type course: int
        """

        self._course = course
