/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {HTML} from '../model/HTML';

/**
* HTML service.
* @module api/HTMLApi
* @version 2.1.0
*/
export class HTMLApi {

    /**
    * Constructs a new HTMLApi. 
    * @alias module:api/HTMLApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the rootGet operation.
     * @callback moduleapi/HTMLApi~rootGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HTML{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * The main INDEX.html
     * @param {module:api/HTMLApi~rootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    rootGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['text/html'];
      let returnType = HTML;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}