/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Course} from '../model/Course';

/**
* Course service.
* @module api/CourseApi
* @version 2.0.0
*/
export class CourseApi {

    /**
    * Constructs a new CourseApi. 
    * @alias module:api/CourseApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the courseById operation.
     * @callback moduleapi/CourseApi~courseByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Course{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a specific course by ID
     * @param {Number} courseId 
     * @param {String} token 
     * @param {module:api/CourseApi~courseByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    courseById(courseId, token, callback) {
      
      let postBody = null;
      // verify the required parameter 'courseId' is set
      if (courseId === undefined || courseId === null) {
        throw new Error("Missing the required parameter 'courseId' when calling courseById");
      }
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling courseById");
      }

      let pathParams = {
        'course_id': courseId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Course;

      return this.apiClient.callApi(
        '/courses/{course_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the courses operation.
     * @callback moduleapi/CourseApi~coursesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Course>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all the courses
     * @param {String} token 
     * @param {module:api/CourseApi~coursesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    courses(token, callback) {
      
      let postBody = null;
      // verify the required parameter 'token' is set
      if (token === undefined || token === null) {
        throw new Error("Missing the required parameter 'token' when calling courses");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Course];

      return this.apiClient.callApi(
        '/courses', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}