/*
 * student-courses
 * The API for the Maryam's homework
 *
 * OpenAPI spec version: 2.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Selection model module.
 * @module model/Selection
 * @version 2.1.0
 */
export class Selection {
  /**
   * Constructs a new <code>Selection</code>.
   * @alias module:model/Selection
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Selection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Selection} obj Optional instance to populate.
   * @return {module:model/Selection} The populated <code>Selection</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Selection();
      if (data.hasOwnProperty('student'))
        obj.student = ApiClient.convertToType(data['student'], 'Number');
      if (data.hasOwnProperty('course'))
        obj.course = ApiClient.convertToType(data['course'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} student
 */
Selection.prototype.student = undefined;

/**
 * @member {Number} course
 */
Selection.prototype.course = undefined;

